// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjfFVovuej_fXlzmAcppy6NN9Oaw0cJQ',
    appId: '1:415999656518:web:f0da8969456b22d6984047',
    messagingSenderId: '415999656518',
    projectId: 'myuecommerce-ed069',
    authDomain: 'myuecommerce-ed069.firebaseapp.com',
    storageBucket: 'myuecommerce-ed069.appspot.com',
    measurementId: 'G-7YG2F2HSB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9doG2V3xGr4N6vq0RU0gqXXWfAsL7oL8',
    appId: '1:415999656518:android:e57eb81195cc5e8a984047',
    messagingSenderId: '415999656518',
    projectId: 'myuecommerce-ed069',
    storageBucket: 'myuecommerce-ed069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAboLHt11tUfaDlImy26SJiB4Sm7MfqgPg',
    appId: '1:415999656518:ios:816ea89c441660aa984047',
    messagingSenderId: '415999656518',
    projectId: 'myuecommerce-ed069',
    storageBucket: 'myuecommerce-ed069.appspot.com',
    iosClientId: '415999656518-90b7qiat5s7f039chjq6r9q2juk9p47v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myucommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAboLHt11tUfaDlImy26SJiB4Sm7MfqgPg',
    appId: '1:415999656518:ios:816ea89c441660aa984047',
    messagingSenderId: '415999656518',
    projectId: 'myuecommerce-ed069',
    storageBucket: 'myuecommerce-ed069.appspot.com',
    iosClientId: '415999656518-90b7qiat5s7f039chjq6r9q2juk9p47v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myucommerce',
  );
}
